require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"

require "user.notify"

require "user.lsp"
require "user.cmp"
require "user.treesitter"
require "user.autopair"
require "user.comment"
require "user.lazygit"
require "user.telescope"
require "user.nvim-tree"
require "user.alpha"
